theme: jekyll-theme-minimal
title: <span style="font-size:0.8em">Reggaeton Punks Stars
layout: default
plugins:
    - jekyll-optional-front-matter
    - jekyll-redirect-from
include:
    -README.md
optional_front_matter:
  remove_originals: true
defaults:
  - scope:
      path: "*.md"
    values:
      layout: default
tagline: THE UNIQUE NFT REGGAETON PUNKS STARS COLLECTION
#twitter:
 #   - username: ...
#social:
 # links:
  #  - https://twitter.com/...
description: Welcome to Reggaeton Punks Stars NFT Project in OpenSea. Collection of 1000 unique and handmade pixelart living in Polygon. Created by JEVARTStudios. </a><p> 

bio:  </a>Created by JEVARTStudios.<p> 

    <i class="fa fa-star" aria-hidden="true"></i>
    <span class="sr-only">OpenSea:</span>&nbsp;&nbsp;<a href="https://opensea.io/collection/reggaetonpunkstars">OpenSea</a><br>
    <i class="fa fa-ticket" aria-hidden="true"></i>
    <span class="sr-only">Metaverse:</span>&nbsp;&nbsp;<a href="https://oncyber.io/reggaetonpunkstars">Metaverse</a><br>
    <i class="fa fa-instagram" aria-hidden="true"></i>
    <span class="sr-only">Instagram:</span>&nbsp;&nbsp;<a href="https://www.instagram.com/reggaetonpunkstars/?hl=es">Instagram</a><br>
    <i class="fa fa-twitter" aria-hidden="true"></i>
    <span class="sr-only">Twitter:</span>&nbsp;&nbsp;<a href="https://twitter.com/reggaeton_nfts">Twitter</a><br>
    <i class="fa fa-spotify" aria-hidden="true"></i>
    <span class="sr-only">Spotify:</span>&nbsp;&nbsp;<a href="https://open.spotify.com/user/31ud2mherrc2yp62n34632ukveqy?si=ddb5227bd8584594&nd=1">Spotify</a><br>
logo: assets/123123.JPG
logo_title: RPS NFT
