theme: jekyll-theme-minimal
title: Reggaeton Punk Stars NFT
layout: default
plugins:
    - jekyll-optional-front-matter
    - jekyll-redirect-from
include:
    -README.md
optional_front_matter:
  remove_originals: true
defaults:
  - scope:
      path: "*.md"
    values:
      layout: default
tagline: THE UNIQUE NFT REGGAETON PUNK STARS COLLECTION
#twitter:
 #   - username: ...
#social:
 # links:
  #  - https://twitter.com/...
description: Welcome to Reggaeton Punks Stars NFT Project in OpenSea. Collection of 100 unique handmade pixelart reggaeton punks stars living in the Polygon. Created by JEVARTStudios. </a><p> 

bio: Welcome to Reggaeton Punks Stars NFT Project in OpenSea. Collection of 100 unique handmade pixelart reggaeton punks stars living in the Polygon. Created by JEVARTStudios. </a><p> 

    <i class="fa fa-envelope-o" aria-hidden="true"></i>
    <span class="sr-only">Mail:</span>&nbsp;&nbsp;<a href="mailto:https://opensea.io/collection/reggaetonpunkstars"> OpenSea account</a><br>
    <i class="fa fa-github" aria-hidden="true"></i>
    <span class="sr-only">GitHub:</span>&nbsp;&nbsp;<a href="https://github.com/reggaetonpunkstarsnft">My GitHub</a>
logo: assets/myfoto.gif
logo_title: Jennifer Gago
