theme: jekyll-theme-minimal
title: Reggaeton Punk Stars NFT
layout: default
plugins:
    - jekyll-optional-front-matter
    - jekyll-redirect-from
include:
    -README.md
optional_front_matter:
  remove_originals: true
defaults:
  - scope:
      path: "*.md"
    values:
      layout: default
tagline: THE UNIQUE NFT REGGAETON PUNK STARS COLLECTION
#twitter:
 #   - username: ...
#social:
 # links:
  #  - https://twitter.com/...
description: Welcome to Reggaeton Punks Stars NFT Project in OpenSea. Collection of 100 unique handmade pixelart reggaeton punks stars living in the Polygon. Created by JEVARTStudios. </a><p> 

bio: Welcome to Reggaeton Punks Stars NFT Project in OpenSea. Collection of 100 unique handmade pixelart reggaeton punks stars living in the Polygon blockchain. Created by JEVARTStudios. </a><p> 

    <i class="fa fa-star" aria-hidden="true"></i>
    <span class="sr-only">OpenSea:</span>&nbsp;&nbsp;<a href="https://opensea.io/collection/reggaetonpunkstars">OpenSea account</a><br>
    <i class="fas fa-vr-cardboard"></i>
    <span class="sr-only">Metaverse:</span>&nbsp;&nbsp;<a href="https://oncyber.io/reggaetonpunkstars">Metaverse</a><br>
    <i class="fa fa-instagram" aria-hidden="true"></i>
    <span class="sr-only">Instagram:</span>&nbsp;&nbsp;<a href="https://www.instagram.com/reggaetonpunkstars/?hl=es">Instagram</a><br>
    <i class="fa fa-twitter" aria-hidden="true"></i>
    <span class="sr-only">Twitter:</span>&nbsp;&nbsp;<a href="https://twitter.com/reggaeton_nfts">Twitter</a>
logo: assets/myfoto.gif
logo_title: REGGAETON PUNK STARS NFT
